@startuml
title Future FindEligible Command Implementation
!include style.puml
skinparam activity {
    BackgroundColor FUTURE_IMPLEMENTATION_COLOUR
    BorderColor black
    ArrowColor FUTURE_IMPLEMENTATION_COLOUR_T4
    FontColor white
}
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12

start
:User inputs FindEligible command;
:Parse user input;

if ()then ([user includes relevant blood type(s)])
    :Create a new FindEligible Command;
    :Creates HasBloodTypePredicate;
    :Creates IsEligibleToDonatePredicate;
    :Filter PersonList using both predicates;
    :Parses the PersonList based on the given user input blood type(s)
     Parses the PersonList based on each person's date of birth and days since last blood donation;
    :Person list is filtered;
    :From the updated person list, the donation record list is updated;
    if () then([filtered PersonList not empty])
        :Update corresponding DonationRecord list;
        :Show updated person and donation record list;
    else([else])
        :Show message: "No eligible donors found";
    endif
else ([no])
    :Show message: "Invalid blood type(s)";
endif
stop
@enduml
