@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":BloodNetParser" as BloodNetParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> BloodNetParser : parseCommand(undo)
activate BloodNetParser

create UndoCommand
BloodNetParser -> UndoCommand
activate UndoCommand

UndoCommand --> BloodNetParser
deactivate UndoCommand

BloodNetParser --> LogicManager : u
deactivate BloodNetParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoBloodNet()
activate Model

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
